name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    container: docker/whalesay:latest
    steps:
      - uses: actions/checkout@v3
      - name: catREADME
        id: catREADME
        run: cat README.md
      - name: cowsay
        uses: Code-Hex/neo-cowsay-action@v1
        with:
          message: | # Support multi-lines
            "${{ steps.catREADME.outputs.content }}"
      

