name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: apt-get update 
      - run: apt-get install cowsay -y 
      - run: ls -l # Liste les fichier du répertoire courant
      - run: cat README.md | cowsay